# Generated by Django 2.2.4 on 2020-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workout_workout_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
